// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ATCDisplay.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ATCDisplay;

public class ATCDLandStrip implements java.lang.Cloneable, java.io.Serializable
{
    public ATCDPosition pos;

    public float width;

    public float length;

    public float orientation;

    public ATCDLandStrip()
    {
    }

    public ATCDLandStrip(ATCDPosition pos, float width, float length, float orientation)
    {
        this.pos = pos;
        this.width = width;
        this.length = length;
        this.orientation = orientation;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ATCDLandStrip _r = null;
        if(rhs instanceof ATCDLandStrip)
        {
            _r = (ATCDLandStrip)rhs;
        }

        if(_r != null)
        {
            if(pos != _r.pos)
            {
                if(pos == null || _r.pos == null || !pos.equals(_r.pos))
                {
                    return false;
                }
            }
            if(width != _r.width)
            {
                return false;
            }
            if(length != _r.length)
            {
                return false;
            }
            if(orientation != _r.orientation)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::ATCDisplay::ATCDLandStrip");
        __h = IceInternal.HashUtil.hashAdd(__h, pos);
        __h = IceInternal.HashUtil.hashAdd(__h, width);
        __h = IceInternal.HashUtil.hashAdd(__h, length);
        __h = IceInternal.HashUtil.hashAdd(__h, orientation);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        pos.__write(__os);
        __os.writeFloat(width);
        __os.writeFloat(length);
        __os.writeFloat(orientation);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        pos = new ATCDPosition();
        pos.__read(__is);
        width = __is.readFloat();
        length = __is.readFloat();
        orientation = __is.readFloat();
    }

    public static final long serialVersionUID = -1698267408853644322L;
}
