// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ATCDisplay.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ATCDisplay;

public interface _AirportInterfaceOperations
{
    java.util.List<ATCDFlight> getFlights(Ice.Current __current);

    ATCDAirport getAirportInfo(Ice.Current __current);

    void UpdateSimT(float inc, Ice.Current __current);

    void NextFocus(Ice.Current __current);

    float getSimT(Ice.Current __current);

    int getMaxFlights(Ice.Current __current);

    int getPoints(Ice.Current __current);
}
