// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `ATCDisplay.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ATCDisplay;

public final class AirportInterfacePrxHolder
{
    public
    AirportInterfacePrxHolder()
    {
    }

    public
    AirportInterfacePrxHolder(AirportInterfacePrx value)
    {
        this.value = value;
    }

    public AirportInterfacePrx value;
}
